---
blank_issues_enabled: false
contact_links:
  - name: 社区支持 - Community Discussions Support
    url: https://github.com/Yuzhii0718/bl-mt798x-dhcpd/discussions
    about: 在此处进行问答 - Please ask and answer questions here.