# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_WEBUI_FAILSAFE_UI_BOOTSTRAP) 	+= fsdata-bootstrap/
obj-$(CONFIG_WEBUI_FAILSAFE_UI_GL) 			+= fsdata-gl/
obj-$(CONFIG_WEBUI_FAILSAFE_UI_MTK) 		+= fsdata-mtk/
