/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2026 Yuzhii0718
 *
 * All rights reserved.
 *
 * This file is part of the project bl-mt798x-dhcpd
 * You may not use, copy, modify or distribute this file except in compliance with the license agreement.
 *
 * Failsafe environment management
 */

#include <env.h>
#include <env_internal.h>
#include <errno.h>
#include <malloc.h>
#include <linux/kernel.h>
#include <linux/string.h>
#include <net/mtk_httpd.h>

#include "../failsafe_internal.h"

#define ENV_NAME_MAX_LEN 128

#ifdef CONFIG_WEBUI_FAILSAFE_ENV_CUSTOM_ENV
#define CUSTOM_ENV_LOADED_FLAG "failsafe_custom_env_loaded"

static const unsigned char custom_env_data[] = {
#include <generated/customenv_autogenerated.h>
};

static int failsafe_env_apply_custom_env(void)
{
	const char *val;
	const unsigned char *p;
	int ret = 0;

	val = env_get(CUSTOM_ENV_LOADED_FLAG);
	if (val)
		return 0;

	for (p = custom_env_data; *p; p += strlen((const char *)p) + 1) {
		const char *eq;
		char *name, *value;
		size_t name_len;

		eq = strchr((const char *)p, '=');
		if (!eq)
			continue;

		name_len = eq - (const char *)p;
		if (!name_len)
			continue;

		name = malloc(name_len + 1);
		if (!name) {
			ret = -ENOMEM;
			break;
		}

		memcpy(name, p, name_len);
		name[name_len] = '\0';

		if (env_get(name)) {
			free(name);
			continue;
		}

		value = strdup(eq + 1);
		if (!value) {
			free(name);
			ret = -ENOMEM;
			break;
		}

		ret = env_set(name, value);
		free(name);
		free(value);
		if (ret)
			break;
	}

	if (!ret) {
		ret = env_set(CUSTOM_ENV_LOADED_FLAG, "1");
		if (!ret)
			ret = env_save();
		printf("Applied custom env from defenvs/custom_env\n");
	}

	if (ret)
		printf("Warning: failed to apply custom env\n");

	return ret;
}
#endif

#ifdef CONFIG_WEBUI_FAILSAFE_ENV_DEFAULT_GLBTN_KEY
static void failsafe_env_ensure_default_glbtn_key(void)
{
	const char *val;
	int ret;

	val = env_get("glbtn_key");
	if (val)
		return;

	ret = env_set("glbtn_key", "reset,wps,mesh");
	if (!ret) {
		ret = env_save();
		printf("Set default glbtn_key env to 'reset,wps,mesh'\n");
	}

	if (ret)
		printf("Warning: failed to set default glbtn_key env\n");
}
#endif

static void failsafe_env_prepare(void)
{
#ifdef CONFIG_WEBUI_FAILSAFE_ENV_CUSTOM_ENV
	(void)failsafe_env_apply_custom_env();
#endif

#ifdef CONFIG_WEBUI_FAILSAFE_ENV_DEFAULT_GLBTN_KEY
	failsafe_env_ensure_default_glbtn_key();
#endif
}

static int failsafe_env_get_form_value(struct httpd_request *request,
	const char *key, char **out, size_t max_len, bool allow_empty)
{
	struct httpd_form_value *v;
	char *buf;
	size_t n;

	if (!request || !key || !out)
		return -EINVAL;

	v = httpd_request_find_value(request, key);
	if (!v || !v->data) {
		if (allow_empty) {
			buf = strdup("");
			if (!buf)
				return -ENOMEM;
			*out = buf;
			return 0;
		}
		return -EINVAL;
	}

	n = v->size;
	if (!allow_empty && !n)
		return -EINVAL;
	if (n > max_len)
		return -E2BIG;

	buf = malloc(n + 1);
	if (!buf)
		return -ENOMEM;

	memcpy(buf, v->data, n);
	buf[n] = '\0';
	*out = buf;
	return 0;
}

static char *failsafe_env_export_text(size_t *out_len)
{
	env_t *envbuf;
	char *out;
	size_t out_sz, i, n;

	if (out_len)
		*out_len = 0;

	envbuf = malloc(sizeof(*envbuf));
	if (!envbuf)
		return NULL;

	if (env_export(envbuf)) {
		free(envbuf);
		return NULL;
	}

	out_sz = ENV_SIZE + 2;
	out = malloc(out_sz);
	if (!out) {
		free(envbuf);
		return NULL;
	}

	n = 0;
	for (i = 0; i < ENV_SIZE - 1; i++) {
		if (!envbuf->data[i] && !envbuf->data[i + 1])
			break;

		out[n++] = envbuf->data[i] ? envbuf->data[i] : '\n';
		if (n + 1 >= out_sz)
			break;
	}

	if (n && out[n - 1] != '\n')
		out[n++] = '\n';

	out[n] = '\0';
	if (out_len)
		*out_len = n;

	free(envbuf);
	return out;
}

void env_list_handler(enum httpd_uri_handler_status status,
	struct httpd_request *request,
	struct httpd_response *response)
{
	char *out;
	size_t out_len = 0;

	if (status == HTTP_CB_CLOSED) {
		failsafe_free_session(status, response);
		return;
	}

	if (status != HTTP_CB_NEW)
		return;

	if (!request || request->method != HTTP_GET) {
		failsafe_http_reply_text(response, 405, "method");
		return;
	}

	failsafe_env_prepare();

	out = failsafe_env_export_text(&out_len);
	if (!out) {
		failsafe_http_reply_text(response, 500, "export failed");
		return;
	}

	response->status = HTTP_RESP_STD;
	response->data = out;
	response->size = out_len;
	response->info.code = 200;
	response->info.connection_close = 1;
	response->info.content_type = "text/plain";
	response->session_data = out;
}

void env_set_handler(enum httpd_uri_handler_status status,
	struct httpd_request *request,
	struct httpd_response *response)
{
	char *name = NULL, *value = NULL;
	int ret;

	if (status != HTTP_CB_NEW)
		return;

	if (!request || request->method != HTTP_POST) {
		failsafe_http_reply_text(response, 405, "method");
		return;
	}

	failsafe_env_prepare();

	ret = failsafe_env_get_form_value(request, "name", &name,
		ENV_NAME_MAX_LEN, false);
	if (ret) {
		failsafe_http_reply_text(response, 400, "bad name");
		return;
	}

	ret = failsafe_env_get_form_value(request, "value", &value,
		ENV_SIZE - 1, true);
	if (ret) {
		free(name);
		failsafe_http_reply_text(response, 400, "bad value");
		return;
	}

	ret = env_set(name, value);
	if (!ret)
		ret = env_save();

	free(name);
	free(value);

	if (ret) {
		failsafe_http_reply_text(response, 500, "save failed");
		return;
	}

	failsafe_http_reply_text(response, 200, "ok");
}

void env_unset_handler(enum httpd_uri_handler_status status,
	struct httpd_request *request,
	struct httpd_response *response)
{
	char *name = NULL;
	int ret;

	if (status != HTTP_CB_NEW)
		return;

	if (!request || request->method != HTTP_POST) {
		failsafe_http_reply_text(response, 405, "method");
		return;
	}

	failsafe_env_prepare();

	ret = failsafe_env_get_form_value(request, "name", &name,
		ENV_NAME_MAX_LEN, false);
	if (ret) {
		failsafe_http_reply_text(response, 400, "bad name");
		return;
	}

	ret = env_set(name, NULL);
	if (!ret)
		ret = env_save();

	free(name);

	if (ret) {
		failsafe_http_reply_text(response, 500, "save failed");
		return;
	}

	failsafe_http_reply_text(response, 200, "ok");
}

void env_reset_handler(enum httpd_uri_handler_status status,
	struct httpd_request *request,
	struct httpd_response *response)
{
	int ret;

	if (status != HTTP_CB_NEW)
		return;

	if (!request || request->method != HTTP_POST) {
		failsafe_http_reply_text(response, 405, "method");
		return;
	}

	env_set_default(NULL, 0);
	failsafe_env_prepare();
	ret = env_save();

	if (ret) {
		failsafe_http_reply_text(response, 500, "save failed");
		return;
	}

	failsafe_http_reply_text(response, 200, "ok");
}

void env_restore_handler(enum httpd_uri_handler_status status,
	struct httpd_request *request,
	struct httpd_response *response)
{
	struct httpd_form_value *fw;
	int ret;

	if (status != HTTP_CB_NEW)
		return;

	if (!request || request->method != HTTP_POST) {
		failsafe_http_reply_text(response, 405, "method");
		return;
	}

	fw = httpd_request_find_value(request, "envfile");
	if (!fw || !fw->data || fw->size < sizeof(env_t)) {
		failsafe_http_reply_text(response, 400, "bad file");
		return;
	}

	ret = env_import((const char *)fw->data, 1, 0);
	if (!ret)
		failsafe_env_prepare();
	if (!ret)
		ret = env_save();

	if (ret) {
		failsafe_http_reply_text(response, 500, "restore failed");
		return;
	}

	failsafe_http_reply_text(response, 200, "ok");
}

void env_size_handler(enum httpd_uri_handler_status status,
	struct httpd_request *request,
	struct httpd_response *response)
{
	env_t *envbuf;
	char *out;
	size_t used_size = 0;
	size_t total_size = ENV_SIZE;
	int ret;

	if (status == HTTP_CB_CLOSED) {
		failsafe_free_session(status, response);
		return;
	}

	if (status != HTTP_CB_NEW)
		return;

	if (!request || request->method != HTTP_GET) {
		failsafe_http_reply_text(response, 405, "method");
		return;
	}

	envbuf = malloc(sizeof(*envbuf));
	if (!envbuf) {
		failsafe_http_reply_text(response, 500, "alloc failed");
		return;
	}

	if (env_export(envbuf)) {
		free(envbuf);
		failsafe_http_reply_text(response, 500, "export failed");
		return;
	}

	/* Calculate used size: find the end of environment data */
	for (size_t i = 0; i < ENV_SIZE - 1; i++) {
		if (!envbuf->data[i] && !envbuf->data[i + 1]) {
			used_size = i + 2; /* Include the double null terminator */
			break;
		}
	}

	/* If we didn't find the end, the env is full */
	if (used_size == 0)
		used_size = ENV_SIZE;

	free(envbuf);

	/* Format response: "used/total bytes" */
	out = malloc(64);
	if (!out) {
		failsafe_http_reply_text(response, 500, "alloc failed");
		return;
	}

	ret = snprintf(out, 64, "%zu/%zu bytes", used_size, total_size);
	if (ret < 0 || ret >= 64) {
		free(out);
		failsafe_http_reply_text(response, 500, "format failed");
		return;
	}

	response->status = HTTP_RESP_STD;
	response->data = out;
	response->size = strlen(out);
	response->info.code = 200;
	response->info.connection_close = 1;
	response->info.content_type = "text/plain";
	response->session_data = out;
}

#ifdef CONFIG_WEBUI_FAILSAFE_ENV
void env_register_handlers(struct httpd_instance *inst)
{
	httpd_register_uri_handler(inst, "/env.html", &html_handler, NULL);
	httpd_register_uri_handler(inst, "/env_js.js", &js_handler, NULL);
	httpd_register_uri_handler(inst, "/env/list", &env_list_handler, NULL);
	httpd_register_uri_handler(inst, "/env/set", &env_set_handler, NULL);
	httpd_register_uri_handler(inst, "/env/unset", &env_unset_handler, NULL);
	httpd_register_uri_handler(inst, "/env/reset", &env_reset_handler, NULL);
	httpd_register_uri_handler(inst, "/env/restore", &env_restore_handler, NULL);
	httpd_register_uri_handler(inst, "/env/size", &env_size_handler, NULL);
}
#endif
